// What Board.begin() does on the M5StackCoreS3, recorded for the golden.
//
// The include is the spelling the README recommends, so the test walks
// the same path a user does.
//
// Generated by tools/gen_boards.py.
#include <TinyM5BoardCoreS3.h>
#include <tinym5_trace.h>
#include <tinym5_model_i2c.h>

void setup()
{
  Serial.begin(115200);
  TinyM5Trace::start("CoreS3");

  // The AXP2101 answers instead, which is the other half of the branch
  // begin() takes. Same address, different id.
  TinyM5Trace::useChip(0, 0x34, 0x03, 0x4A);
  // This chip reports millivolts directly (0x0FA0 == 4000) and has a real
  // fuel gauge in 0xA4, so the level is read rather than estimated.
  TinyM5Trace::model().set(0x34, 0x0F);
  TinyM5Trace::model().set(0x35, 0xA0);
  TinyM5Trace::model().set(0xA4, 87);
  // The expander answers too, and identifies itself through 0x10.
  TinyM5Trace::addChip(0, 0x58, 0x10, 0x23);

  Board.begin();

  TinyM5Trace::finish();
}

void loop() { delay(10); }
