"""Tier 0 - every board header, through the toolchain that ships the code.

The begin() goldens run on the host core. They answer "does the bring-up
do the right things in the right order", and they answer it for a
compiler that is not the one a user builds with. This tier answers the
other half: does the header for this board compile for the SoC that board
actually has.

Nothing runs. A zero exit from `arduino-cli compile` is the whole result,
and the sketches carry their own expectations as `static_assert` and
`#error` so that a wrong answer is a compile error rather than something
this file has to check by hand.

The sketches under `boards/` are generated by tools/gen_boards.py - a
board without a tier 0 sketch would be a board nobody notices breaking.
The two under `entry/` are hand written, because they are about the entry
point rather than about any board.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

TIER0 = Path(__file__).parent
BOARDS = sorted(p.parent for p in TIER0.glob("boards/*/sketch.yaml"))

pytestmark = pytest.mark.skipif(
    shutil.which("arduino-cli") is None, reason="arduino-cli is not on PATH")


def compile_sketch(directory):
    # No FQBN and no core install here: sketch.yaml pins both, and its
    # default profile is what `compile` uses (D29).
    return subprocess.run(["arduino-cli", "compile"], cwd=directory,
                          capture_output=True, text=True, timeout=900)


def test_catalogue_is_present():
    assert BOARDS, "no tier 0 sketches - run tools/gen_boards.py"


@pytest.mark.parametrize("sketch", BOARDS, ids=lambda p: p.name)
def test_board_header_compiles(sketch):
    r = compile_sketch(sketch)
    assert r.returncode == 0, f"{sketch.name}:\n{r.stdout}\n{r.stderr}"


def test_board_header_macro():
    """The string spelling of the entry point, and the default global."""
    r = compile_sketch(TIER0 / "entry" / "BoardHeaderMacro")
    assert r.returncode == 0, f"{r.stdout}\n{r.stderr}"


def test_two_board_headers_stop_the_build():
    """The one test here that passes by failing."""
    r = compile_sketch(TIER0 / "entry" / "DoubleInclude")
    assert r.returncode != 0, "two board headers in one sketch built anyway"
    assert "one board per sketch" in r.stdout + r.stderr, (
        f"it failed, but not on the guard:\n{r.stdout}\n{r.stderr}")
