"""begin() golden for M5StickC Plus2 (StickCPlus2).

One directory per board because the plugin's `dut` fixture is module
scoped and the build follows the sketch directory: sharing one sketch
across boards makes the second module talk to the first one's process.

Generated by tools/gen_boards.py - a board without a test is a board
nobody would notice breaking.
"""

from tinym5_check import check_begin


def test_begin(dut, request):
    check_begin(dut, request, "StickCPlus2")
