// What Board.begin() does on the M5ChainCaptain, recorded for the golden.
//
// The include is the spelling the README recommends, so the test walks
// the same path a user does.
//
// Generated by tools/gen_boards.py.
#include <TinyM5BoardChainCaptain.h>
#include <tinym5_trace.h>
#include <tinym5_model_i2c.h>

void setup()
{
  Serial.begin(115200);
  TinyM5Trace::start("ChainCaptain");

  // The M5PM1 has to answer at its own address, 0x6E rather than 0x34.
  // Its id is four bytes and the driver only checks that the read
  // succeeded, the same as M5Stack's own library.
  TinyM5Trace::useChip(0, 0x6E, 0x00, 0x50);
  // Millivolts, little-endian: 0x0FA0 == 4000. No fuel gauge on this chip,
  // so the level in the golden is the estimate from that voltage.
  TinyM5Trace::model().set(0x22, 0xA0);
  TinyM5Trace::model().set(0x23, 0x0F);
  // The expander answers as well. Two chips on one bus is why the model is
  // a list rather than a single register file.
  TinyM5Trace::addChip(0, 0x4F, 0x00, 0x01);

  Board.begin();

  TinyM5Trace::finish();
}

void loop() { delay(10); }
