// Tier 0 for the M5StampS3: does this header stand on its own?
//
// Nothing here runs. What it proves is that the toolchain that ships the
// code accepts this board's header for the SoC the board actually has,
// that the build-flag entry point reaches it, and that the feature
// macros and the constants beside them say the same thing.
//
// Generated by tools/gen_boards.py.

// The global instance is opt-out, and defining one of our own is what
// proves the switch works: if the header had made one too, this would
// not compile.
#define TINYM5_NO_GLOBAL_BOARD

// Named by a macro rather than by an include. The begin() tests take the
// direct include, so between the two tiers both spellings are covered.
#define TINYM5_STAMPS3
#include <TinyM5Board.h>

TINYM5_BOARD Board;

#if !defined(TINYM5_HAS_DISPLAY) \
    || !defined(TINYM5_HAS_BACKLIGHT) \
    || !defined(TINYM5_HAS_BATTERY) \
    || !defined(TINYM5_HAS_INTERNAL_I2C) \
    || !defined(TINYM5_HAS_EXTERNAL_I2C) \
    || !defined(TINYM5_HAS_RGB_LED) \
    || !defined(TINYM5_HAS_BTN_A) \
    || !defined(TINYM5_HAS_BTN_B) \
    || !defined(TINYM5_HAS_BTN_C) \
    || !defined(TINYM5_HAS_BTN_PWR)
#error "TinyM5Board: a feature macro is missing. Portable sketches ask with #if, so one that is absent on a board is a sketch that stops being portable there."
#endif

static_assert(TINYM5_BOARD::kBoardId == TinyM5::BoardId::StampS3,
              "the entry point selected a different board");
static_assert(TINYM5_BOARD::kFamily == TinyM5::Family::Stamp,
              "family does not match the catalogue");

// Macro against constant, for every flag that has a constant to compare
// with.
static_assert(TINYM5_HAS_DISPLAY == TINYM5_BOARD::kHasDisplay, "display");
static_assert(TINYM5_HAS_BACKLIGHT == TINYM5_BOARD::kHasBacklight, "backlight");
static_assert(TINYM5_HAS_BATTERY == TINYM5_BOARD::kHasBattery, "battery");
static_assert(TINYM5_HAS_INTERNAL_I2C == TINYM5_BOARD::kHasInternalI2c, "internal I2C");
static_assert(TINYM5_HAS_EXTERNAL_I2C == TINYM5_BOARD::kHasExternalI2c, "external I2C");
static_assert(TINYM5_HAS_RGB_LED == (TINYM5_BOARD::kRgbLed >= 0), "RGB LED");

// The pin lookup and the constants are two spellings of one answer
// (D28), so they cannot be allowed to drift apart.
static_assert(TINYM5_BOARD::getPin(TinyM5::Pin::InI2cSda) == TINYM5_BOARD::kI2cSda, "sda");
static_assert(TINYM5_BOARD::getPin(TinyM5::Pin::InI2cScl) == TINYM5_BOARD::kI2cScl, "scl");
static_assert(TINYM5_BOARD::getPin(TinyM5::Pin::ExI2cSda) == TINYM5_BOARD::kI2cExtSda, "ext sda");
static_assert(TINYM5_BOARD::getPin(TinyM5::Pin::ExI2cScl) == TINYM5_BOARD::kI2cExtScl, "ext scl");
static_assert(TINYM5_BOARD::getPin(TinyM5::Pin::RgbLed) == TINYM5_BOARD::kRgbLed, "led");
static_assert(TINYM5_BOARD::getPin(TinyM5::Pin::PowerHold) == TINYM5_BOARD::kPowerHold, "hold");

// Every feature path, compiled for the real target. A sketch reaches
// these through the same #if, so anything that only works on the host
// shows up here.
void setup()
{
  Board.begin();
  Serial.println(Board.getBoardName());
}

void loop()
{
  Board.update();
  if (Board.BtnA.wasClicked() || Board.BtnA.wasDoubleClicked()
      || Board.BtnA.wasHold()) {
    Serial.println(Board.BtnA.getClickCount());
  }
}
