// What Board.begin() does on the M5StampPLC, recorded for the golden.
//
// The include is the spelling the README recommends, so the test walks
// the same path a user does.
//
// Generated by tools/gen_boards.py.
#include <TinyM5BoardStampPLC.h>
#include <tinym5_trace.h>
#include <tinym5_model_i2c.h>

void setup()
{
  Serial.begin(115200);
  TinyM5Trace::start("StampPLC");

  // The expander is the only chip on this board's bus. Its id register
  // only has to be non-zero, and the button pins read high (released)
  // because the model starts every register at zero... so seed them.
  TinyM5Trace::useChip(0, 0x43, 0x01, 0xA0);
  TinyM5Trace::model().set(0x0F, 0xFF);

  Board.begin();

  TinyM5Trace::finish();
}

void loop() { delay(10); }
