// What Board.begin() does on the ArduinoNessoN1, recorded for the golden.
//
// The include is the spelling the README recommends, so the test walks
// the same path a user does.
//
// Generated by tools/gen_boards.py.
#include <TinyM5BoardNessoN1.h>
#include <tinym5_trace.h>
#include <tinym5_model_i2c.h>

void setup()
{
  Serial.begin(115200);
  TinyM5Trace::start("NessoN1");

  // The charger answers with its id, which is the same as its address.
  TinyM5Trace::useChip(0, 0x49, 0x0A, 0x49);
  // The gauge next to it reports millivolts little-endian in 0x08: 0x0FA0
  // is 4000, so the golden shows the assembly rather than a plausible
  // number.
  TinyM5Trace::addChip(0, 0x55, 0x08, 0xA0).set(0x09, 0x0F);
  // Two expanders on one bus, at the two addresses the chip can take.
  TinyM5Trace::addChip(0, 0x43, 0x01, 0xA0).set(0x07, 0xFF);
  TinyM5Trace::addChip(0, 0x44, 0x01, 0xA0).set(0x07, 0xFF);

  Board.begin();

  TinyM5Trace::finish();
}

void loop() { delay(10); }
