// What Board.begin() does on the M5AtomLite, recorded for the golden.
//
// The include is the spelling the README recommends, so the test walks
// the same path a user does.
//
// Generated by tools/gen_boards.py.
#include <TinyM5BoardAtomLite.h>
#include <tinym5_trace.h>

void setup()
{
  Serial.begin(115200);
  TinyM5Trace::start("AtomLite");

  Board.begin();

  TinyM5Trace::finish();
}

void loop() { delay(10); }
