// What Board.begin() does on the M5StickC, recorded for the golden.
//
// The include is the spelling the README recommends, so the test walks
// the same path a user does.
//
// Generated by tools/gen_boards.py.
#include <TinyM5BoardStickC.h>
#include <tinym5_trace.h>
#include <tinym5_model_i2c.h>

void setup()
{
  Serial.begin(115200);
  TinyM5Trace::start("StickC");

  // The AXP192 has to answer or begin() stops at its
  // detection read and the rest of the trace never happens.
  TinyM5Trace::useChip(0, 0x34, 0x03, 0x03);

  Board.begin();

  TinyM5Trace::finish();
}

void loop() { delay(10); }
