// Board identifiers. The numbers match m5stack-board-id, so they can
// be compared with M5GFX and M5Unified without depending on either.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#include <stdint.h>

namespace TinyM5 {

enum class BoardId : uint16_t {
  Unknown = 0,
  Core2 = 2,
  StickC = 6,
  CoreInk = 6,
  Paper = 7,
  Tough = 8,
  Station = 9,
  CoreS3 = 10,
  Dial = 12,
  DinMeter = 13,
  StickCPlus = 13,
  Cardputer = 14,
  AirQ = 15,
  VAMeter = 16,
  StickCPlus2 = 17,
  CoreS3SE = 17,
  StampPLC = 21,
  NessoN1 = 23,
  StickS3 = 26,
  StackChan = 27,
  PaperMono = 29,
  StopWatch = 30,
  CoreP4X = 31,
  ChainCaptain = 32,
  AtomLite = 128,
  AtomU = 130,
  TimerCam = 132,
  StampPico = 133,
  StampC3 = 134,
  StampC3U = 135,
  StampS3 = 136,
  AtomS3Lite = 137,
  AtomS3U = 138,
  Capsule = 139,
  NanoC6 = 140,
  AtomMatrix = 141,
  AtomVoice = 142,
  NanoH2 = 151,
};

}  // namespace TinyM5
