// Board identifiers. The numbers match m5stack-board-id, so they can
// be compared with M5GFX and M5Unified without depending on either.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#include <stdint.h>

namespace TinyM5 {

enum class BoardId : uint16_t {
  Unknown = 0,
  Core2 = 2,
  StickC = 6,
  Tough = 8,
  Station = 9,
  CoreS3 = 10,
  StickCPlus = 13,
  StickCPlus2 = 17,
  CoreS3SE = 17,
  StampPLC = 21,
  StickS3 = 26,
  StackChan = 27,
  ChainCaptain = 32,
  AtomLite = 128,
  AtomU = 130,
  TimerCam = 132,
  StampPico = 133,
  AtomS3Lite = 137,
  AtomS3U = 138,
  Capsule = 139,
  AtomMatrix = 141,
  AtomVoice = 142,
};

}  // namespace TinyM5
