// TinyM5BoardCoreS3
//
// An AXP2101 for power and an AW9523B for the rest. The panel's
// reset is P1_1 on the expander, so no pin on the SoC touches it.
// The CoreS3 SE and the StackChan share this bring-up; they differ
// only in the camera and a second expander, neither of which is
// power or display.
// **GPIO 35 is both the SPI MISO and the panel's D/C.** A graphics
// library driving this screen has to re-point that pin on every CS
// transition; this library reports both roles and does not perform
// that trick - it belongs inside the SPI transaction layer.
// Its A/B/C are touch zones, not GPIOs. The SD card shares the
// LCD's SPI bus and is not yet taken out of SD mode.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerAxp2101.h"
#include "TinyM5Board/SdSpiMode.h"
#include "TinyM5Board/IoExpanderAw9523.h"
#include "TinyM5Board/BacklightAxp2101.h"

class TinyM5BoardCoreS3 {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::CoreS3;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Core;
  static constexpr const char *kName = "M5StackCoreS3";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 12;
  static constexpr int8_t kI2cScl = 11;
  static constexpr int8_t kI2cExtSda = 2;
  static constexpr int8_t kI2cExtScl = 1;
  static constexpr int8_t kPowerHold = -1;
  /// The TF card's chip select. The card shares the panel's SPI bus
  /// on this board, so begin() has to quieten it before anything
  /// reads the panel.
  static constexpr int8_t kSdSpiCs = 4;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnPwr = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerAxp2101 Power;

  // ---- I/O expander ----
  // Not spare pins: at least one line the panel needs is in here.
  TinyM5BoardIoExpanderAw9523 Io;

  // ---- backlight ----
  TinyM5BoardBacklightAxp2101<TinyM5::Axp2101Light::Dldo1> Backlight{Power};

  // ---- buttons ----
  // Some of these are not pins on the SoC - they live in the
  // power chip or the expander and are read over I2C, so those
  // are rate limited to the debounce interval.
  TinyM5BoardButton BtnPwr{
      [](void *p) {
        return static_cast<TinyM5BoardPowerAxp2101 *>(p)->isKeyPressed();
      },
      &Power, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    const bool ok = Power.begin(Wire);
    const bool ioOk = Io.begin(Wire);
    // Every one of the sixteen expander pins comes up in LED-driver mode, so
    // saying "these are GPIOs" is not optional. 1 = input for the direction,
    // 1 = plain GPIO for the mode. (M5GFX.cpp, the CoreS3 branch)
    Io.setDirections(0b00011000, 0b00001100);
    Io.setPushPullP0();
    Io.setGpioMode(0xFF, 0xFF);
    // P1_0 and P1_1 high: the second is the panel's reset line. The VBUS 5V
    // output (P1_7) is left off - see the note above.
    Io.setOutputs(0b00000101, 0b00000011);
    Io.resetPulse(TinyM5BoardIoExpanderAw9523::Io::P1_1);
    // ALDO3 is the camera rail and ALDO4 the TF slot. Upstream enables both
    // on all three of these boards, including the SE that has no camera, so
    // this is transcribed rather than trimmed.
    Power.setLdoEnables(0xBF);
    Power.setAldo3Millivolt(3300);
    Power.setAldo4Millivolt(3300);
    // The card is on the panel's wires. Left in SD mode it answers
    // the panel id read that a graphics library starts with.
    TinyM5::sdToSpiMode(/*sclk*/ 36, /*miso*/ 35,
                        /*mosi*/ 37, kSdSpiCs);
    Backlight.begin();
    return ok && ioOk;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*mosi*/ 37, /*miso*/ 35, /*sclk*/ 36,
        /*dc*/ 35, /*cs*/ 3,
        /*rst*/ -1,  // begin() has already pulsed it
        /*busy*/ -1,
        /*freqWrite*/ 40000000, /*freqRead*/ 16000000,
        /*width*/ 320, /*height*/ 240,
        /*offsetX*/ 0, /*offsetY*/ 0,
        /*rotation*/ 3, /*invert*/ true,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 0
#define TINYM5_HAS_BTN_B 0
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardCoreS3

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardCoreS3 Board;
#endif
