// TinyM5BoardStickC
//
// The original Stick. Without the AXP192 rails the screen stays
// black however correct the SPI wiring is - the single most common
// way to get stuck on this board.
// Its panel wants a gamma command after init (CMD_GAMMASET 0x08)
// that a graphics library has to send; this library does not drive
// panels.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerAxp192.h"
#include "TinyM5Board/BacklightAxp192.h"

class TinyM5BoardStickC {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::StickC;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Stick;
  static constexpr const char *kName = "M5StickC";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 21;
  static constexpr int8_t kI2cScl = 22;
  static constexpr int8_t kI2cExtSda = 32;
  static constexpr int8_t kI2cExtScl = 33;
  static constexpr int8_t kPowerHold = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = 37;
  static constexpr int8_t kBtnB = 39;
  static constexpr int8_t kBtnPwr = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  // The rails this board's schematic actually uses, and the voltages
  // that are not the chip's default. The driver knows which bit is
  // which; the board knows what they feed.
  TinyM5BoardPowerAxp192 Power{TinyM5BoardPowerAxp192::Dcdc1 | TinyM5BoardPowerAxp192::Ldo2 | TinyM5BoardPowerAxp192::Ldo3 | TinyM5BoardPowerAxp192::Exten};

  // ---- backlight ----
  TinyM5BoardBacklightAxp192<TinyM5::Axp192Light::Ldo2> Backlight{Power};

  // ---- buttons ----
  TinyM5BoardButton BtnA{[] { return digitalRead(kBtnA) == LOW; }};
  TinyM5BoardButton BtnB{[] { return digitalRead(kBtnB) == LOW; }};
  // No pin: the power key lives in the PMIC and is read over
  // I2C, rate limited so update() does not flood the bus.
  TinyM5BoardButton BtnPwr{
      [](void *p) {
        return static_cast<TinyM5BoardPowerAxp192 *>(p)->getKeyState() != 0;
      },
      &Power, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    pinMode(kBtnA, INPUT);
    pinMode(kBtnB, INPUT);
    // The chip is soldered on, so no answer is a real fault. The
    // rails have to be up before the panel is taken out of reset.
    const bool ok = Power.begin(Wire);
    TinyM5::resetPulse(18);
    Backlight.begin();
    return ok;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*mosi*/ 15, /*miso*/ 14, /*sclk*/ 13,
        /*dc*/ 23, /*cs*/ 5,
        /*rst*/ -1,  // begin() has already pulsed it
        /*freqWrite*/ 27000000, /*freqRead*/ 14000000,
        /*width*/ 80, /*height*/ 160,
        /*offsetX*/ 26, /*offsetY*/ 1,
        /*rotation*/ 2, /*invert*/ true,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardStickC

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardStickC Board;
#endif
