// TinyM5BoardPaper
//
// The original 960x540 electrophoretic tablet, on a classic ESP32.
// Its IT8951 controller takes commands as SPI words rather than
// through a D/C pin, and holds BUSY (GPIO 27) while it refreshes.
// The card is on the panel's bus, so begin() quietens it first.
// GPIO 5 switches the 5 V output on the Grove port. It is left
// configured and off: what is plugged in is not something a board
// bring-up gets to guess (D35).
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerAdc.h"
#include "TinyM5Board/SdSpiMode.h"

class TinyM5BoardPaper {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::Paper;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Paper;
  static constexpr const char *kName = "M5Paper";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 21;
  static constexpr int8_t kI2cScl = 22;
  static constexpr int8_t kI2cExtSda = 25;
  static constexpr int8_t kI2cExtScl = 32;
  static constexpr int8_t kPowerHold = 2;
  /// The TF card's chip select. The card shares the panel's SPI bus
  /// on this board, so begin() has to quieten it before anything
  /// reads the panel.
  static constexpr int8_t kSdSpiCs = 4;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = 37;
  static constexpr int8_t kBtnB = 38;
  static constexpr int8_t kBtnC = 39;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = false;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerAdc Power{35, 2000};

  // ---- buttons ----
  TinyM5BoardButton BtnA{[] { return digitalRead(kBtnA) == LOW; }};
  TinyM5BoardButton BtnB{[] { return digitalRead(kBtnB) == LOW; }};
  TinyM5BoardButton BtnC{[] { return digitalRead(kBtnC) == LOW; }};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    holdPower();
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    pinMode(kBtnA, INPUT);
    pinMode(kBtnB, INPUT);
    pinMode(kBtnC, INPUT);
    Power.begin();
    // The Grove port's 5 V switch. Configured but not turned on - see the
    // note above. (M5Unified Power_Class.cpp:632)
    pinMode(5, OUTPUT);
    digitalWrite(5, LOW);
    TinyM5::resetPulse(23);
    // The panel holds this line while it refreshes. Nothing here
    // waits on it, but a floating pin would make the driver's first
    // read a coin toss.
    pinMode(27, INPUT);
    // The card is on the panel's wires. Left in SD mode it answers
    // the panel id read that a graphics library starts with.
    TinyM5::sdToSpiMode(/*sclk*/ 14, /*miso*/ 13,
                        /*mosi*/ 12, kSdSpiCs);
    return true;
  }

  /// Latch the power rail on. Called by begin(), and safe to call
  /// first thing in setup() when begin() cannot run that early.
  static void holdPower()
  {
    pinMode(kPowerHold, OUTPUT);
    digitalWrite(kPowerHold, HIGH);
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnC.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*bus*/ TinyM5::DisplayBus::Spi,
        /*mosi*/ 12, /*miso*/ 13, /*sclk*/ 14,
        /*dc*/ -1, /*cs*/ 15,
        /*io2*/ -1, /*io3*/ -1,
        /*rst*/ -1,  // begin() has already pulsed it
        /*busy*/ 27,
        /*freqWrite*/ 40000000, /*freqRead*/ 20000000,
        /*width*/ 960, /*height*/ 540,
        /*offsetX*/ 0, /*offsetY*/ 0,
        /*rotation*/ 3, /*invert*/ false,
        /*threeWire*/ false};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 0
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_DISPLAY_DSI 0
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 1
#define TINYM5_HAS_BTN_PWR 0

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardPaper

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardPaper Board;
#endif
