// TinyM5BoardChainCaptain
//
// Two M5Stack chips side by side: an M5PM1 for power and an M5IOE1
// for everything the panel needs. Its supply is IO12 and its reset
// is IO1, both on the expander, so no GPIO on the SoC touches the
// screen at all.
// Both chips sleep on an idle bus and keep that setting across a
// power cycle, which is why begin() clears it on each of them.
// M5GFX also requires OPI-PSRAM here, for its own framebuffer; this
// library allocates nothing and does not care.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerM5pm1.h"
#include "TinyM5Board/IoExpanderM5ioe1.h"
#include "TinyM5Board/BacklightM5ioe1.h"

class TinyM5BoardChainCaptain {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::ChainCaptain;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Core;
  static constexpr const char *kName = "M5ChainCaptain";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 3;
  static constexpr int8_t kI2cScl = 2;
  static constexpr int8_t kI2cExtSda = 7;
  static constexpr int8_t kI2cExtScl = 6;
  static constexpr int8_t kPowerHold = -1;
  /// -1: no card on the panel's SPI bus.
  static constexpr int8_t kSdSpiCs = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = 1;
  static constexpr int8_t kBtnB = 4;
  static constexpr int8_t kBtnC = 5;
  static constexpr int8_t kBtnPwr = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerM5pm1 Power{0};

  // ---- I/O expander ----
  // Not spare pins: at least one line the panel needs is in here.
  TinyM5BoardIoExpanderM5ioe1 Io;

  // ---- backlight ----
  TinyM5BoardBacklightM5ioe1 Backlight{
      Io, TinyM5BoardIoExpanderM5ioe1::Pwm::Ch3,
      TinyM5BoardIoExpanderM5ioe1::Io::Io11, 1000};

  // ---- buttons ----
  // Some of these are not pins on the SoC - they live in the
  // power chip or the expander and are read over I2C, so those
  // are rate limited to the debounce interval.
  TinyM5BoardButton BtnA{[] { return digitalRead(kBtnA) == LOW; }};
  TinyM5BoardButton BtnB{[] { return digitalRead(kBtnB) == LOW; }};
  TinyM5BoardButton BtnC{[] { return digitalRead(kBtnC) == LOW; }};
  TinyM5BoardButton BtnPwr{
      [](void *p) {
        return static_cast<TinyM5BoardPowerM5pm1 *>(p)->isKeyPressed();
      },
      &Power, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    pinMode(kBtnA, INPUT_PULLUP);
    pinMode(kBtnB, INPUT_PULLUP);
    pinMode(kBtnC, INPUT_PULLUP);
    // The idle-sleep timeout and the watchdog are disabled in here;
    // both survive a power cycle and both can make this board look
    // dead if something else set them.
    const bool ok = Power.begin(Wire);
    // Same idle-sleep trap as the PMIC, and the same fix.
    const bool ioOk = Io.begin(Wire);
    // IO12 switches the panel's supply and IO1 is its reset line. Neither is
    // a pin on the SoC. (M5GFX.cpp, the ChainCaptain branch)
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io12);
    Io.resetPulse(TinyM5BoardIoExpanderM5ioe1::Io::Io1);
    // The audio amplifier comes up enabled and pops. Silence it here; making
    // it play is the sketch's business, not the board's.
    pinMode(21, OUTPUT);
    digitalWrite(21, LOW);
    Backlight.begin();
    return ok && ioOk;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnC.update(ms);
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*bus*/ TinyM5::DisplayBus::Spi,
        /*mosi*/ 16, /*miso*/ -1, /*sclk*/ 15,
        /*dc*/ 46, /*cs*/ 45,
        /*io2*/ -1, /*io3*/ -1,
        /*rst*/ -1,  // this panel has no reset pin of its own
        /*busy*/ -1,
        /*freqWrite*/ 40000000, /*freqRead*/ 16000000,
        /*width*/ 240, /*height*/ 240,
        /*offsetX*/ 0, /*offsetY*/ 0,
        /*rotation*/ 2, /*invert*/ true,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_DISPLAY_DSI 0
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 1
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardChainCaptain

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardChainCaptain Board;
#endif
