// TinyM5BoardStopWatch
//
// A round AMOLED on four data lines. This is the first QSPI panel
// here, and the reason TinyM5::Display carries a bus kind at all:
// mosi and miso are io0 and io1 rather than a direction each, io2
// and io3 are the other two, and there is no D/C pin - the command
// rides in the transfer's instruction phase.
// Brightness is a panel command on an AMOLED, so there is no
// backlight here for this library to own.
// The same two chips as the PaperMono: an M5PM1 for power and an
// M5IOE1 for the panel's reset, the touch layer and the audio
// amplifier - which is left off, because a board bring-up that
// makes a noise is a bug.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerM5pm1.h"
#include "TinyM5Board/IoExpanderM5ioe1.h"

class TinyM5BoardStopWatch {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::StopWatch;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Other;
  static constexpr const char *kName = "M5StopWatch";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 47;
  static constexpr int8_t kI2cScl = 48;
  static constexpr int8_t kI2cExtSda = 10;
  static constexpr int8_t kI2cExtScl = 11;
  static constexpr int8_t kPowerHold = -1;
  /// -1: no card on the panel's SPI bus.
  static constexpr int8_t kSdSpiCs = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = 2;
  static constexpr int8_t kBtnB = 1;
  static constexpr int8_t kBtnPwr = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = false;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerM5pm1 Power{TinyM5BoardPowerM5pm1::Charge | TinyM5BoardPowerM5pm1::Dcdc5V | TinyM5BoardPowerM5pm1::Ldo3V3 | TinyM5BoardPowerM5pm1::Led};

  // ---- I/O expander ----
  // Not spare pins: at least one line the panel needs is in here.
  TinyM5BoardIoExpanderM5ioe1 Io;

  // ---- buttons ----
  // Some of these are not pins on the SoC - they live in the
  // power chip or the expander and are read over I2C, so those
  // are rate limited to the debounce interval.
  TinyM5BoardButton BtnA{[] { return digitalRead(kBtnA) == LOW; }};
  TinyM5BoardButton BtnB{[] { return digitalRead(kBtnB) == LOW; }};
  TinyM5BoardButton BtnPwr{
      [](void *p) {
        return static_cast<TinyM5BoardPowerM5pm1 *>(p)->isKeyPressed();
      },
      &Power, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    pinMode(kBtnA, INPUT_PULLUP);
    pinMode(kBtnB, INPUT_PULLUP);
    // The idle-sleep timeout and the watchdog are disabled in here;
    // both survive a power cycle and both can make this board look
    // dead if something else set them.
    const bool ok = Power.begin(Wire);
    // Same idle-sleep trap as the PMIC, and the same fix.
    const bool ioOk = Io.begin(Wire);
    // The panel's chip select is a real pin and goes high before anything
    // touches the bus. (M5GFX.cpp, the StopWatch branch)
    pinMode(39, OUTPUT);
    digitalWrite(39, HIGH);
    // On the expander: IO1 is the mux control, IO4 the touch layer's reset,
    // IO5 the panel's, IO8 a rail, and IO3 the audio amplifier.
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io1);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io4);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io5);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io8);
    // The amplifier's enable is configured but left low. Bringing a board up
    // is not an excuse to make a noise.
    Io.setPushPull(TinyM5BoardIoExpanderM5ioe1::Io::Io3);
    Io.setOutput(TinyM5BoardIoExpanderM5ioe1::Io::Io3);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io3, false);
    delay(10);
    // The panel and the touch layer come out of reset together.
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io4, false);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io5, false);
    delay(8);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io4, true);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io5, true);
    delay(2);
    // The second half of the amplifier, on IO10.
    Io.setPushPull(TinyM5BoardIoExpanderM5ioe1::Io::Io10);
    Io.setOutput(TinyM5BoardIoExpanderM5ioe1::Io::Io10);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io10, false);
    // The panel's tearing-effect line. An input the driver may wait on; it
    // is pulled up here so that first read is not a coin toss.
    pinMode(38, INPUT_PULLUP);
    return ok && ioOk;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*bus*/ TinyM5::DisplayBus::QSpi,
        /*mosi*/ 41, /*miso*/ 42, /*sclk*/ 40,
        /*dc*/ -1, /*cs*/ 39,
        /*io2*/ 46, /*io3*/ 45,
        /*rst*/ -1,  // begin() has already pulsed it
        /*busy*/ -1,
        /*freqWrite*/ 80000000, /*freqRead*/ 1000000,
        /*width*/ 468, /*height*/ 468,
        /*offsetX*/ 6, /*offsetY*/ 0,
        /*rotation*/ 0, /*invert*/ false,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 0
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardStopWatch

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardStopWatch Board;
#endif
