// TinyM5BoardStickS3
//
// The Stick with M5Stack's own PMIC instead of an AXP192. Nothing
// reaches the panel until the chip's GPIO2 is driven high, and the
// chip itself stops answering if its idle-sleep timeout was ever
// set - a setting that survives a power cycle. begin() clears it
// every time for that reason.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerM5pm1.h"
#include "TinyM5Board/BacklightPwm.h"

class TinyM5BoardStickS3 {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::StickS3;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Stick;
  static constexpr const char *kName = "M5StickS3";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 47;
  static constexpr int8_t kI2cScl = 48;
  static constexpr int8_t kI2cExtSda = 9;
  static constexpr int8_t kI2cExtScl = 10;
  static constexpr int8_t kPowerHold = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = 11;
  static constexpr int8_t kBtnB = 12;
  static constexpr int8_t kBtnPwr = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerM5pm1 Power{0};

  // ---- backlight ----
  TinyM5BoardBacklightPwm Backlight{38, 256, 16};

  // ---- buttons ----
  TinyM5BoardButton BtnA{[] { return digitalRead(kBtnA) == LOW; }};
  TinyM5BoardButton BtnB{[] { return digitalRead(kBtnB) == LOW; }};
  // No pin: the power key lives in the PMIC and is read over
  // I2C, rate limited so update() does not flood the bus.
  TinyM5BoardButton BtnPwr{
      [](void *p) {
        return static_cast<TinyM5BoardPowerM5pm1 *>(p)->isKeyPressed();
      },
      &Power, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    pinMode(kBtnA, INPUT_PULLUP);
    pinMode(kBtnB, INPUT_PULLUP);
    // The idle-sleep timeout and the watchdog are disabled in here;
    // both survive a power cycle and both can make this board look
    // dead if something else set them.
    const bool ok = Power.begin(Wire);
    // GPIO2 switches L3B, which is the panel's supply. Push-pull output,
    // driven high, then a moment for the rail to settle before the reset.
    // (M5GFX.cpp, the StickS3 branch)
    Power.gpioEnableRail(TinyM5BoardPowerM5pm1::Gpio::Io2);
    delay(100);
    TinyM5::resetPulse(21);
    Backlight.begin();
    return ok;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*mosi*/ 39, /*miso*/ -1, /*sclk*/ 40,
        /*dc*/ 45, /*cs*/ 41,
        /*rst*/ -1,  // begin() has already pulsed it
        /*freqWrite*/ 40000000, /*freqRead*/ 16000000,
        /*width*/ 135, /*height*/ 240,
        /*offsetX*/ 52, /*offsetY*/ 40,
        /*rotation*/ 0, /*invert*/ true,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardStickS3

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardStickS3 Board;
#endif
