// TinyM5BoardStampPLC
//
// A DIN-rail controller. Its three front buttons are not pins:
// they hang off the PI4IO expander, so reading one costs an I2C
// transaction and Board.BtnA is rate limited accordingly.
// The backlight is the same expander's P7 and is a plain switch -
// on or off, nothing between. Board.Backlight.dimmable() says so.
// The SD card shares the LCD's SPI bus and is not yet taken out of
// SD mode.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/SdSpiMode.h"
#include "TinyM5Board/IoExpanderPi4io.h"
#include "TinyM5Board/BacklightPi4io.h"

class TinyM5BoardStampPLC {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::StampPLC;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Stamp;
  static constexpr const char *kName = "M5StampPLC";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 13;
  static constexpr int8_t kI2cScl = 15;
  static constexpr int8_t kI2cExtSda = 2;
  static constexpr int8_t kI2cExtScl = 1;
  static constexpr int8_t kPowerHold = -1;
  /// The TF card's chip select. The card shares the panel's SPI bus
  /// on this board, so begin() has to quieten it before anything
  /// reads the panel.
  static constexpr int8_t kSdSpiCs = 10;
  static constexpr int8_t kRgbLed = 21;
  static constexpr uint8_t kRgbLedCount = 1;
  static constexpr int8_t kBtnA = -1;
  static constexpr int8_t kBtnB = -1;
  static constexpr int8_t kBtnC = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = false;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- I/O expander ----
  // Not spare pins: at least one line the panel needs is in here.
  TinyM5BoardIoExpanderPi4io Io;

  // ---- backlight ----
  // On/off only - this board has no way to dim.
  TinyM5BoardBacklightPi4io Backlight{
      Io, TinyM5BoardIoExpanderPi4io::Io::P7, true};

  // ---- buttons ----
  // Some of these are not pins on the SoC - they live in the
  // power chip or the expander and are read over I2C, so those
  // are rate limited to the debounce interval.
  TinyM5BoardButton BtnA{
      [](void *p) {
        return !static_cast<TinyM5BoardIoExpanderPi4io *>(p)->read(
            TinyM5BoardIoExpanderPi4io::Io::P2);
      },
      &Io, true};
  TinyM5BoardButton BtnB{
      [](void *p) {
        return !static_cast<TinyM5BoardIoExpanderPi4io *>(p)->read(
            TinyM5BoardIoExpanderPi4io::Io::P1);
      },
      &Io, true};
  TinyM5BoardButton BtnC{
      [](void *p) {
        return !static_cast<TinyM5BoardIoExpanderPi4io *>(p)->read(
            TinyM5BoardIoExpanderPi4io::Io::P0);
      },
      &Io, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    const bool ioOk = Io.begin(Wire);
    // The buttons are expander inputs with pull-ups. They also have to come
    // out of high impedance - out of reset every pin on this chip drives
    // nothing. (M5Unified.cpp, the StampPLC case)
    Io.enableInput(TinyM5BoardIoExpanderPi4io::Io::P0);
    Io.enableInput(TinyM5BoardIoExpanderPi4io::Io::P1);
    Io.enableInput(TinyM5BoardIoExpanderPi4io::Io::P2);
    TinyM5::resetPulse(3);
    // The card is on the panel's wires. Left in SD mode it answers
    // the panel id read that a graphics library starts with.
    TinyM5::sdToSpiMode(/*sclk*/ 7, /*miso*/ 9,
                        /*mosi*/ 8, kSdSpiCs);
    Backlight.begin();
    return true && ioOk;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnC.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*mosi*/ 8, /*miso*/ 9, /*sclk*/ 7,
        /*dc*/ 6, /*cs*/ 12,
        /*rst*/ -1,  // begin() has already pulsed it
        /*freqWrite*/ 40000000, /*freqRead*/ 16000000,
        /*width*/ 135, /*height*/ 240,
        /*offsetX*/ 52, /*offsetY*/ 40,
        /*rotation*/ 1, /*invert*/ true,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 0
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 1
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 1
#define TINYM5_HAS_BTN_PWR 0

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardStampPLC

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardStampPLC Board;
#endif
