// TinyM5Board - build-flag entry point.
//
// The direct spelling is preferred and is what the examples use:
//
//     #include <TinyM5BoardAtomLite.h>
//
// This header is the other way in, for when the board comes from the
// build system rather than the source - a CI matrix over every board,
// or a PlatformIO env per board:
//
//     #define TINYM5_ATOMLITE
//     #include <TinyM5Board.h>
//
// Some build systems can only pass a string. For those there is
// TINYM5_BOARD_HEADER, which takes the header name itself:
//
//     -DTINYM5_BOARD_HEADER="TinyM5BoardAtomLite.h"
//
// Arduino's own board macros are never consulted. Picking a
// near-enough board in the IDE because yours is not in the list is
// common, and ARDUINO_M5STACK_CORE2 cannot tell a v1.0 from a v1.1
// even when it is correct, so guessing from them would manufacture
// wrong answers rather than find right ones.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#include "TinyM5Board/Common.h"

#if defined(TINYM5_BOARD)
// A board header was included directly. Nothing to choose.
#elif defined(TINYM5_BOARD_HEADER)
// Named as a string. This header has already put the library on the
// include path, so the computed include resolves from there.
#include TINYM5_BOARD_HEADER
#elif defined(TINYM5_ATOMLITE)
#include "TinyM5BoardAtomLite.h"
#elif defined(TINYM5_ATOMMATRIX)
#include "TinyM5BoardAtomMatrix.h"
#elif defined(TINYM5_ATOMU)
#include "TinyM5BoardAtomU.h"
#elif defined(TINYM5_ATOMVOICE)
#include "TinyM5BoardAtomVoice.h"
#elif defined(TINYM5_ATOMS3LITE)
#include "TinyM5BoardAtomS3Lite.h"
#elif defined(TINYM5_ATOMS3U)
#include "TinyM5BoardAtomS3U.h"
#elif defined(TINYM5_TIMERCAM)
#include "TinyM5BoardTimerCam.h"
#elif defined(TINYM5_CAPSULE)
#include "TinyM5BoardCapsule.h"
#elif defined(TINYM5_DIAL)
#include "TinyM5BoardDial.h"
#elif defined(TINYM5_DINMETER)
#include "TinyM5BoardDinMeter.h"
#elif defined(TINYM5_NANOC6)
#include "TinyM5BoardNanoC6.h"
#elif defined(TINYM5_NANOH2)
#include "TinyM5BoardNanoH2.h"
#elif defined(TINYM5_STICKCPLUS2)
#include "TinyM5BoardStickCPlus2.h"
#elif defined(TINYM5_STICKC)
#include "TinyM5BoardStickC.h"
#elif defined(TINYM5_STICKCPLUS)
#include "TinyM5BoardStickCPlus.h"
#elif defined(TINYM5_STATION)
#include "TinyM5BoardStation.h"
#elif defined(TINYM5_TOUGH)
#include "TinyM5BoardTough.h"
#elif defined(TINYM5_CORE2)
#include "TinyM5BoardCore2.h"
#elif defined(TINYM5_STICKS3)
#include "TinyM5BoardStickS3.h"
#elif defined(TINYM5_CHAINCAPTAIN)
#include "TinyM5BoardChainCaptain.h"
#elif defined(TINYM5_CORES3)
#include "TinyM5BoardCoreS3.h"
#elif defined(TINYM5_CORES3SE)
#include "TinyM5BoardCoreS3SE.h"
#elif defined(TINYM5_STACKCHAN)
#include "TinyM5BoardStackChan.h"
#elif defined(TINYM5_PAPERMONO)
#include "TinyM5BoardPaperMono.h"
#elif defined(TINYM5_STAMPPICO)
#include "TinyM5BoardStampPico.h"
#elif defined(TINYM5_STAMPS3)
#include "TinyM5BoardStampS3.h"
#elif defined(TINYM5_STAMPC3)
#include "TinyM5BoardStampC3.h"
#elif defined(TINYM5_STAMPC3U)
#include "TinyM5BoardStampC3U.h"
#elif defined(TINYM5_STAMPPLC)
#include "TinyM5BoardStampPLC.h"
#else
#error "TinyM5Board: no board selected. Include the header for your board (for example <TinyM5BoardAtomLite.h>), or define its macro (for example TINYM5_ATOMLITE) before including this one. The board list is in the README."
#endif
