// TinyM5BoardToughC5
//
// The Tough on an ESP32-C5, with the M5PM1 and M5IOE1 pair in
// place of the AXP192. Its A/B/C are touch zones rather than
// pins, like the Tough's.
// Port A is the internal bus, physically split through a level
// shifter, so kSharesI2cBus is true.
// The panel's reset and supply are expander pins and the touch
// layer's reset is a power-chip pin, so nothing on the SoC drives
// any of them. Its card shares the panel's SPI bus.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerM5pm1.h"
#include "TinyM5Board/SdSpiMode.h"
#include "TinyM5Board/IoExpanderM5ioe1.h"
#include "TinyM5Board/BacklightM5ioe1.h"

class TinyM5BoardToughC5 {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::ToughC5;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Core;
  static constexpr const char *kName = "M5ToughC5";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 2;
  static constexpr int8_t kI2cScl = 3;
  static constexpr int8_t kI2cExtSda = 2;
  static constexpr int8_t kI2cExtScl = 3;
  static constexpr int8_t kPowerHold = -1;
  /// The TF card's chip select. The card shares the panel's SPI bus
  /// on this board, so begin() has to quieten it before anything
  /// reads the panel.
  static constexpr int8_t kSdSpiCs = 10;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnPwr = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = true;

  // ---- power ----
  TinyM5BoardPowerM5pm1 Power{TinyM5BoardPowerM5pm1::Charge | TinyM5BoardPowerM5pm1::Dcdc5V | TinyM5BoardPowerM5pm1::Ldo3V3 | TinyM5BoardPowerM5pm1::Led};

  // ---- I/O expander ----
  // Not spare pins: at least one line the panel needs is in here.
  TinyM5BoardIoExpanderM5ioe1 Io;

  // ---- backlight ----
  TinyM5BoardBacklightM5ioe1 Backlight{
      Io, TinyM5BoardIoExpanderM5ioe1::Pwm::Ch4,
      TinyM5BoardIoExpanderM5ioe1::Io::Io10, 1000};

  // ---- buttons ----
  // Some of these are not pins on the SoC - they live in the
  // power chip or the expander and are read over I2C, so those
  // are rate limited to the debounce interval.
  TinyM5BoardButton BtnPwr{
      [](void *p) {
        return static_cast<TinyM5BoardPowerM5pm1 *>(p)->isKeyPressed();
      },
      &Power, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
    }
    // The idle-sleep timeout and the watchdog are disabled in here;
    // both survive a power cycle and both can make this board look
    // dead if something else set them.
    const bool ok = Power.begin(Wire);
    // Same idle-sleep trap as the PMIC, and the same fix.
    const bool ioOk = Io.begin(Wire);
    // IO4 is the panel's reset and IO5 its supply. The reset line has no
    // pull-up on the board, so the output latch is written high *before* the
    // pin becomes an output - the other order drives it low for as long as
    // the two I2C transactions take, which resets the panel.
    // (M5GFX.cpp, the ToughC5 branch)
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io4, true);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io5, true);
    Io.setPushPull(TinyM5BoardIoExpanderM5ioe1::Io::Io4);
    Io.setPushPull(TinyM5BoardIoExpanderM5ioe1::Io::Io5);
    Io.setOutput(TinyM5BoardIoExpanderM5ioe1::Io::Io4);
    Io.setOutput(TinyM5BoardIoExpanderM5ioe1::Io::Io5);
    Io.resetPulse(TinyM5BoardIoExpanderM5ioe1::Io::Io4);
    // The touch layer's reset is GPIO2 inside the power chip, and takes the
    // same care for the same reason.
    Power.gpioWrite(TinyM5BoardPowerM5pm1::Gpio::Io2, true);
    Power.gpioFunctionGpio(TinyM5BoardPowerM5pm1::Gpio::Io2);
    Power.gpioOutput(TinyM5BoardPowerM5pm1::Gpio::Io2);
    Power.gpioPushPull(TinyM5BoardPowerM5pm1::Gpio::Io2);
    Power.gpioResetPulse(TinyM5BoardPowerM5pm1::Gpio::Io2);
    // The card is on the panel's wires. Left in SD mode it answers
    // the panel id read that a graphics library starts with.
    TinyM5::sdToSpiMode(/*sclk*/ 9, /*miso*/ 8,
                        /*mosi*/ 7, kSdSpiCs);
    Backlight.begin();
    return ok && ioOk;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*bus*/ TinyM5::DisplayBus::Spi,
        /*mosi*/ 7, /*miso*/ 8, /*sclk*/ 9,
        /*dc*/ 26, /*cs*/ 25,
        /*io2*/ -1, /*io3*/ -1,
        /*rst*/ -1,  // this panel has no reset pin of its own
        /*busy*/ -1,
        /*freqWrite*/ 40000000, /*freqRead*/ 16000000,
        /*width*/ 320, /*height*/ 240,
        /*offsetX*/ 0, /*offsetY*/ 0,
        /*rotation*/ 3, /*invert*/ true,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_DISPLAY_DSI 0
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 0
#define TINYM5_HAS_BTN_B 0
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_EXT 0
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardToughC5

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardToughC5 Board;
#endif
