// TinyM5BoardStickCPlus2
//
// The Stick without a PMIC. POWER_HOLD on GPIO 4 is what keeps it
// alive: let go of the power button before that pin is high and the
// board switches itself off.
// The pinout moved from the StickC Plus - DC is 14 (was 23) and RST
// is 12 (was 18).
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerAdc.h"
#include "TinyM5Board/BacklightPwm.h"

class TinyM5BoardStickCPlus2 {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::StickCPlus2;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Stick;
  static constexpr const char *kName = "M5StickC Plus2";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 21;
  static constexpr int8_t kI2cScl = 22;
  static constexpr int8_t kI2cExtSda = 32;
  static constexpr int8_t kI2cExtScl = 33;
  static constexpr int8_t kPowerHold = 4;
  /// -1: no card on the panel's SPI bus.
  static constexpr int8_t kSdSpiCs = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = 37;
  static constexpr int8_t kBtnB = 39;
  static constexpr int8_t kBtnPwr = 35;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerAdc Power{38, 2000};

  // ---- backlight ----
  TinyM5BoardBacklightPwm Backlight{27, 256, 40};

  // ---- buttons ----
  TinyM5BoardButton BtnA{[] { return digitalRead(kBtnA) == LOW; }};
  TinyM5BoardButton BtnB{[] { return digitalRead(kBtnB) == LOW; }};
  TinyM5BoardButton BtnPwr{[] { return digitalRead(kBtnPwr) == LOW; }};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    holdPower();
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    pinMode(kBtnA, INPUT);
    pinMode(kBtnB, INPUT);
    pinMode(kBtnPwr, INPUT);
    Power.begin();
    TinyM5::resetPulse(12);
    Backlight.begin();
    return true;
  }

  /// Latch the power rail on. Called by begin(), and safe to call
  /// first thing in setup() when begin() cannot run that early.
  static void holdPower()
  {
    pinMode(kPowerHold, OUTPUT);
    digitalWrite(kPowerHold, HIGH);
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*mosi*/ 15, /*miso*/ -1, /*sclk*/ 13,
        /*dc*/ 14, /*cs*/ 5,
        /*rst*/ -1,  // begin() has already pulsed it
        /*freqWrite*/ 40000000, /*freqRead*/ 15000000,
        /*width*/ 135, /*height*/ 240,
        /*offsetX*/ 52, /*offsetY*/ 40,
        /*rotation*/ 0, /*invert*/ true,
        /*threeWire*/ false};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardStickCPlus2

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardStickCPlus2 Board;
#endif
