// TinyM5Board - build-flag entry point.
//
// The direct spelling is preferred and is what the examples use:
//
//     #include <TinyM5BoardAtomLite.h>
//
// This header is the other way in, for when the board comes from the
// build system rather than the source - a CI matrix over every board,
// or a PlatformIO env per board:
//
//     #define TINYM5_ATOMLITE
//     #include <TinyM5Board.h>
//
// Some build systems can only pass a string. For those there is
// TINYM5_BOARD_HEADER, which takes the header name itself:
//
//     -DTINYM5_BOARD_HEADER="TinyM5BoardAtomLite.h"
//
// Arduino's own board macros are never consulted. Picking a
// near-enough board in the IDE because yours is not in the list is
// common, and ARDUINO_M5STACK_CORE2 cannot tell a v1.0 from a v1.1
// even when it is correct, so guessing from them would manufacture
// wrong answers rather than find right ones.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#include "TinyM5Board/Common.h"

#if defined(TINYM5_BOARD)
// A board header was included directly. Nothing to choose.
#elif defined(TINYM5_BOARD_HEADER)
// Named as a string. This header has already put the library on the
// include path, so the computed include resolves from there.
#include TINYM5_BOARD_HEADER
#elif defined(TINYM5_ATOMLITE)
#include "TinyM5BoardAtomLite.h"
#elif defined(TINYM5_TIMERCAM)
#include "TinyM5BoardTimerCam.h"
#elif defined(TINYM5_CAPSULE)
#include "TinyM5BoardCapsule.h"
#elif defined(TINYM5_STICKCPLUS2)
#include "TinyM5BoardStickCPlus2.h"
#else
#error "TinyM5Board: no board selected. Include the header for your board (for example <TinyM5BoardAtomLite.h>), or define its macro (for example TINYM5_ATOMLITE) before including this one. The board list is in the README."
#endif
