// TinyM5BoardPaperMono
//
// An 800x480 electrophoretic panel, and the first board here whose
// screen is not an LCD. The bus is still plain SPI - what an EPD
// adds is the BUSY line, GPIO 18, which the controller holds for
// the hundreds of milliseconds a refresh takes.
// An M5PM1 for power and an M5IOE1 for the rest: the panel's
// supply, its reset, the touch layer and the card slot are all
// expander pins. The front light is a PWM channel inside the
// M5PM1 rather than a pin.
// Its card is on a bus of its own, so nothing has to be quietened
// before the panel is read.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerM5pm1.h"
#include "TinyM5Board/IoExpanderM5ioe1.h"
#include "TinyM5Board/BacklightM5pm1.h"

class TinyM5BoardPaperMono {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::PaperMono;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Paper;
  static constexpr const char *kName = "M5PaperMono";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 47;
  static constexpr int8_t kI2cScl = 48;
  static constexpr int8_t kI2cExtSda = -1;
  static constexpr int8_t kI2cExtScl = -1;
  static constexpr int8_t kPowerHold = -1;
  /// -1: no card on the panel's SPI bus.
  static constexpr int8_t kSdSpiCs = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = 2;
  static constexpr int8_t kBtnB = 3;
  static constexpr int8_t kBtnPwr = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = false;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerM5pm1 Power{TinyM5BoardPowerM5pm1::Charge | TinyM5BoardPowerM5pm1::Dcdc5V | TinyM5BoardPowerM5pm1::Ldo3V3 | TinyM5BoardPowerM5pm1::Led};

  // ---- I/O expander ----
  // Not spare pins: at least one line the panel needs is in here.
  TinyM5BoardIoExpanderM5ioe1 Io;

  // ---- backlight ----
  TinyM5BoardBacklightM5pm1 Backlight{
      Power, TinyM5BoardPowerM5pm1::Pwm::Ch0,
      TinyM5BoardPowerM5pm1::Gpio::Io3, 5000};

  // ---- buttons ----
  // Some of these are not pins on the SoC - they live in the
  // power chip or the expander and are read over I2C, so those
  // are rate limited to the debounce interval.
  TinyM5BoardButton BtnA{[] { return digitalRead(kBtnA) == LOW; }};
  TinyM5BoardButton BtnB{[] { return digitalRead(kBtnB) == LOW; }};
  TinyM5BoardButton BtnPwr{
      [](void *p) {
        return static_cast<TinyM5BoardPowerM5pm1 *>(p)->isKeyPressed();
      },
      &Power, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
    }
    pinMode(kBtnA, INPUT_PULLUP);
    pinMode(kBtnB, INPUT_PULLUP);
    // The idle-sleep timeout and the watchdog are disabled in here;
    // both survive a power cycle and both can make this board look
    // dead if something else set them.
    const bool ok = Power.begin(Wire);
    // Same idle-sleep trap as the PMIC, and the same fix.
    const bool ioOk = Io.begin(Wire);
    // The panel's chip select is a real pin and has to be high before
    // anything else touches the bus. (M5GFX.cpp, the PaperMono branch)
    pinMode(16, OUTPUT);
    digitalWrite(16, HIGH);
    // Everything else the panel needs is on the expander: IO3 is its supply,
    // IO5 its reset, IO6 the touch layer's reset, IO13 the touch layer's
    // supply and IO14 the card slot's.
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io3);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io13);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io14);
    Io.setPushPull(TinyM5BoardIoExpanderM5ioe1::Io::Io5);
    Io.setOutput(TinyM5BoardIoExpanderM5ioe1::Io::Io5);
    Io.setPushPull(TinyM5BoardIoExpanderM5ioe1::Io::Io6);
    Io.setOutput(TinyM5BoardIoExpanderM5ioe1::Io::Io6);
    // The panel and the touch layer come out of reset together.
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io5, false);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io6, false);
    delay(8);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io5, true);
    Io.write(TinyM5BoardIoExpanderM5ioe1::Io::Io6, true);
    delay(2);
    // The panel holds this line while it refreshes. Nothing here
    // waits on it, but a floating pin would make the driver's first
    // read a coin toss.
    pinMode(18, INPUT);
    Backlight.begin();
    return ok && ioOk;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*bus*/ TinyM5::DisplayBus::Spi,
        /*mosi*/ 14, /*miso*/ -1, /*sclk*/ 15,
        /*dc*/ 17, /*cs*/ 16,
        /*io2*/ -1, /*io3*/ -1,
        /*rst*/ -1,  // this panel has no reset pin of its own
        /*busy*/ 18,
        /*freqWrite*/ 40000000, /*freqRead*/ 10000000,
        /*width*/ 800, /*height*/ 480,
        /*offsetX*/ 0, /*offsetY*/ 0,
        /*rotation*/ 3, /*invert*/ false,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_DISPLAY_DSI 0
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 0
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_EXT 0
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardPaperMono

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardPaperMono Board;
#endif
