// TinyM5BoardCoreP4X
//
// An ESP32-P4 with a MIPI-DSI panel - the first board here whose
// screen has no pins at all. The lanes come out of the DSI
// peripheral, so what is board knowledge is how many are wired,
// how fast they run, which internal LDO feeds the PHY and the
// blanking the glass was cut for. That is displayDsi(); the
// geometry is in display() like everywhere else.
// An M5PM1 for power and an M5IOE1 for the rest: the touch reset,
// the backlight, the panel's supply and reset, and the 3V3 rail
// that MBUS, the card slot, the IMU, the infrared and Ethernet all
// share are expander pins.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerM5pm1.h"
#include "TinyM5Board/IoExpanderM5ioe1.h"
#include "TinyM5Board/BacklightM5ioe1.h"

class TinyM5BoardCoreP4X {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::CoreP4X;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Core;
  static constexpr const char *kName = "M5CoreP4X";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 11;
  static constexpr int8_t kI2cScl = 9;
  static constexpr int8_t kI2cExtSda = 18;
  static constexpr int8_t kI2cExtScl = 16;
  static constexpr int8_t kPowerHold = -1;
  /// -1: no card on the panel's SPI bus.
  static constexpr int8_t kSdSpiCs = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnPwr = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerM5pm1 Power{TinyM5BoardPowerM5pm1::Boost};

  // ---- I/O expander ----
  // Not spare pins: at least one line the panel needs is in here.
  TinyM5BoardIoExpanderM5ioe1 Io;

  // ---- backlight ----
  TinyM5BoardBacklightM5ioe1 Backlight{
      Io, TinyM5BoardIoExpanderM5ioe1::Pwm::Ch1,
      TinyM5BoardIoExpanderM5ioe1::Io::Io9, 1000};

  // ---- buttons ----
  // Some of these are not pins on the SoC - they live in the
  // power chip or the expander and are read over I2C, so those
  // are rate limited to the debounce interval.
  TinyM5BoardButton BtnPwr{
      [](void *p) {
        return static_cast<TinyM5BoardPowerM5pm1 *>(p)->isKeyPressed();
      },
      &Power, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    // The idle-sleep timeout and the watchdog are disabled in here;
    // both survive a power cycle and both can make this board look
    // dead if something else set them.
    const bool ok = Power.begin(Wire);
    // Same idle-sleep trap as the PMIC, and the same fix.
    const bool ioOk = Io.begin(Wire);
    // Five expander pins, all of them supplies or resets: IO8 the touch
    // layer's reset, IO9 the backlight, IO10 the panel's supply, IO11 its
    // reset, and IO12 the 3V3 rail shared by MBUS, the card slot, the IMU,
    // the infrared receiver and Ethernet. (M5GFX.cpp, the CoreP4X branch)
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io8);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io9);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io10);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io11);
    Io.enableRail(TinyM5BoardIoExpanderM5ioe1::Io::Io12);
    // The panel wants its supply settled before anything talks to it.
    delay(150);
    Backlight.begin();
    return ok && ioOk;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*bus*/ TinyM5::DisplayBus::Dsi,
        /*mosi*/ -1, /*miso*/ -1, /*sclk*/ -1,
        /*dc*/ -1, /*cs*/ -1,
        /*io2*/ -1, /*io3*/ -1,
        /*rst*/ -1,  // this panel has no reset pin of its own
        /*busy*/ -1,
        /*freqWrite*/ 0, /*freqRead*/ 0,
        /*width*/ 480, /*height*/ 480,
        /*offsetX*/ 0, /*offsetY*/ 0,
        /*rotation*/ 2, /*invert*/ false,
        /*threeWire*/ false};
  }

  /// The lanes, the PHY's supply and the timings. Everything a
  /// DSI panel needs that a pin number cannot say.
  static constexpr TinyM5::DisplayDsi displayDsi()
  {
    return TinyM5::DisplayDsi{
        /*busId*/ 0, /*laneCount*/ 2,
        /*laneMbps*/ 600,
        /*ldoChannel*/ 3, /*ldoMillivolt*/ 2500,
        /*dpiFreqMhz*/ 24,
        /*hsync*/ 40, 2, 40,
        /*vsync*/ 8, 4, 200};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_DISPLAY_DSI 1
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 0
#define TINYM5_HAS_BTN_B 0
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_EXT 0
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardCoreP4X

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardCoreP4X Board;
#endif
