// TinyM5BoardNessoN1
//
// A LoRa handheld, and the first board here with two expanders.
// One holds the buttons and the radio's control lines; the other
// holds the panel's reset, the backlight and the system rails, so
// both are bring-up rather than devices.
// Its Grove port is the internal bus - one set of pins, level
// shifted - so kSharesI2cBus is true and only Wire is opened.
// Power is a pair too: an AW32001 charger with a BQ27220 gauge
// beside it, because neither answers both questions.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerAw32001.h"
#include "TinyM5Board/IoExpanderPi4io.h"
#include "TinyM5Board/BacklightPi4io.h"

class TinyM5BoardNessoN1 {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::NessoN1;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Other;
  static constexpr const char *kName = "ArduinoNessoN1";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 10;
  static constexpr int8_t kI2cScl = 8;
  static constexpr int8_t kI2cExtSda = 10;
  static constexpr int8_t kI2cExtScl = 8;
  static constexpr int8_t kPowerHold = -1;
  /// -1: no card on the panel's SPI bus.
  static constexpr int8_t kSdSpiCs = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = -1;
  static constexpr int8_t kBtnB = -1;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = true;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = true;

  // ---- power ----
  // Two chips behind one member: the charger and the gauge that
  // measures what it is charging.
  TinyM5BoardPowerAw32001 Power;

  // ---- I/O expander ----
  // Not spare pins: at least one line the panel needs is in here.
  TinyM5BoardIoExpanderPi4io Io;
  // The second one answers at the other address.
  TinyM5BoardIoExpanderPi4io Io2{TinyM5BoardIoExpanderPi4io::kAddressAlt};

  // ---- backlight ----
  // On/off only - this board has no way to dim.
  TinyM5BoardBacklightPi4io Backlight{
      Io2, TinyM5BoardIoExpanderPi4io::Io::P6, false};

  // ---- buttons ----
  // Some of these are not pins on the SoC - they live in the
  // power chip or the expander and are read over I2C, so those
  // are rate limited to the debounce interval.
  TinyM5BoardButton BtnA{
      [](void *p) {
        return !static_cast<TinyM5BoardIoExpanderPi4io *>(p)->read(
            TinyM5BoardIoExpanderPi4io::Io::P0);
      },
      &Io, true};
  TinyM5BoardButton BtnB{
      [](void *p) {
        return !static_cast<TinyM5BoardIoExpanderPi4io *>(p)->read(
            TinyM5BoardIoExpanderPi4io::Io::P1);
      },
      &Io, true};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
    }
    const bool ok = Power.begin(Wire);
    const bool ioOk = Io.begin(Wire);
    const bool ioOk1 = Io2.begin(Wire);
    // The first expander (0x43) is the radio's and the buttons'. P0 and P1
    // are the two front buttons, P2-P4 are unused, P5 the LNA enable, P6 the
    // RF switch and P7 the LoRa module's reset, which is released here.
    // (M5GFX.cpp and M5Unified Power_Class.cpp agree register for register.)
    Io.enableInput(TinyM5BoardIoExpanderPi4io::Io::P0);
    Io.enableInput(TinyM5BoardIoExpanderPi4io::Io::P1);
    Io.setPullNone(TinyM5BoardIoExpanderPi4io::Io::P2);
    Io.setPullNone(TinyM5BoardIoExpanderPi4io::Io::P3);
    Io.setPullNone(TinyM5BoardIoExpanderPi4io::Io::P4);
    Io.enableOutput(TinyM5BoardIoExpanderPi4io::Io::P5, false);
    Io.setPullNone(TinyM5BoardIoExpanderPi4io::Io::P5);
    Io.enableOutput(TinyM5BoardIoExpanderPi4io::Io::P6, false, false);
    Io.enableOutput(TinyM5BoardIoExpanderPi4io::Io::P7, true, false);
    // Only the two buttons may pull the interrupt line. Nothing here waits
    // on it - the buttons are polled - but the board comes up with this mask
    // and changing it is not this library's decision to make.
    Io.setInputDefault(0b00000011);
    Io.setInterruptMask(0b11111100);
    // The second expander (0x44) is the system's. P0 switches the whole
    // board off and stays low, P1 is the panel's reset, P2 the external 5 V,
    // P6 the backlight and P7 the status LED, which is off when high.
    Io2.enableOutput(TinyM5BoardIoExpanderPi4io::Io::P0, false);
    Io2.enableOutput(TinyM5BoardIoExpanderPi4io::Io::P1, false);
    Io2.enableOutput(TinyM5BoardIoExpanderPi4io::Io::P2, false);
    Io2.enableOutput(TinyM5BoardIoExpanderPi4io::Io::P6, false);
    Io2.enableOutput(TinyM5BoardIoExpanderPi4io::Io::P7, true, false);
    // P3 and P4 are not connected and P5 senses VIN. Upstream pulls all
    // three down rather than leaving them floating, and so does this.
    //
    // Upstream also takes P5 out of high impedance. That would enable the
    // driver on a pin the board reads, so it is left as the chip's reset
    // leaves it - the one place here that does not follow M5GFX register
    // for register.
    Io2.setPullDown(TinyM5BoardIoExpanderPi4io::Io::P3);
    Io2.setPullDown(TinyM5BoardIoExpanderPi4io::Io::P4);
    Io2.setPullDown(TinyM5BoardIoExpanderPi4io::Io::P5);
    // The panel's reset is on that expander rather than a pin, so the pulse
    // happens here instead of through TinyM5::resetPulse().
    Io2.resetPulse(TinyM5BoardIoExpanderPi4io::Io::P1);
    Backlight.begin();
    return ok && ioOk && ioOk1;
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*bus*/ TinyM5::DisplayBus::Spi,
        /*mosi*/ 21, /*miso*/ 22, /*sclk*/ 20,
        /*dc*/ 16, /*cs*/ 17,
        /*io2*/ -1, /*io3*/ -1,
        /*rst*/ -1,  // this panel has no reset pin of its own
        /*busy*/ -1,
        /*freqWrite*/ 40000000, /*freqRead*/ 16000000,
        /*width*/ 135, /*height*/ 240,
        /*offsetX*/ 52, /*offsetY*/ 40,
        /*rotation*/ 0, /*invert*/ true,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 1
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_DISPLAY_DSI 0
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 0
#define TINYM5_HAS_BTN_EXT 0
#define TINYM5_HAS_BTN_PWR 0

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardNessoN1

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardNessoN1 Board;
#endif
