// TinyM5BoardCoreInk
//
// A 200x200 electrophoretic panel on a classic ESP32, and the
// board with the most buttons here: A/B/C on the front, an EXT on
// GPIO 5 and a power key on GPIO 27 - a pin rather than a PMIC
// register on this one.
// Two controllers have shipped under the name, a GDEW0154D67 and a
// GDEW0154M09, with the same pins and size.
// Its divider is 25.1/5.1, which is neither of the two ratios the
// other ADC boards use.
//
// Generated by tools/gen_boards.py - edit the catalogue there, not this file.
#pragma once

#ifdef TINYM5_BOARD
#error "TinyM5Board: one board per sketch. A second board header was included, and only the first one would have taken effect - name the one you meant."
#endif

#include <Wire.h>

#include "TinyM5Board/Common.h"
#include "TinyM5Board/Button.h"
#include "TinyM5Board/PowerAdc.h"

class TinyM5BoardCoreInk {
 public:
  // ---- identity ----
  static constexpr TinyM5::BoardId kBoardId = TinyM5::BoardId::CoreInk;
  static constexpr TinyM5::Family kFamily = TinyM5::Family::Paper;
  static constexpr const char *kName = "M5StackCoreInk";

  // ---- pins ----
  static constexpr int8_t kI2cSda = 21;
  static constexpr int8_t kI2cScl = 22;
  static constexpr int8_t kI2cExtSda = 32;
  static constexpr int8_t kI2cExtScl = 33;
  static constexpr int8_t kPowerHold = 12;
  /// -1: no card on the panel's SPI bus.
  static constexpr int8_t kSdSpiCs = -1;
  static constexpr int8_t kRgbLed = -1;
  static constexpr uint8_t kRgbLedCount = 0;
  static constexpr int8_t kBtnA = 37;
  static constexpr int8_t kBtnB = 38;
  static constexpr int8_t kBtnC = 39;
  static constexpr int8_t kBtnExt = 5;
  static constexpr int8_t kBtnPwr = 27;

  // ---- what this board has ----
  // Derived from the catalogue columns, so a flag cannot disagree
  // with the thing it describes.
  static constexpr bool kHasDisplay = true;
  static constexpr bool kHasBacklight = false;
  static constexpr bool kHasBattery = true;
  static constexpr bool kHasInternalI2c = true;
  static constexpr bool kHasExternalI2c = true;
  static constexpr bool kSharesI2cBus = false;

  // ---- power ----
  TinyM5BoardPowerAdc Power{35, 4922};

  // ---- buttons ----
  TinyM5BoardButton BtnA{[] { return digitalRead(kBtnA) == LOW; }};
  TinyM5BoardButton BtnB{[] { return digitalRead(kBtnB) == LOW; }};
  TinyM5BoardButton BtnC{[] { return digitalRead(kBtnC) == LOW; }};
  TinyM5BoardButton BtnExt{[] { return digitalRead(kBtnExt) == LOW; }};
  TinyM5BoardButton BtnPwr{[] { return digitalRead(kBtnPwr) == LOW; }};

  bool begin(uint8_t flags = TinyM5::InitDefault)
  {
    holdPower();
    if (!(flags & TinyM5::KeepSerial)) {
      Serial.begin(115200);
    }
    if (!(flags & TinyM5::KeepI2c)) {
      Wire.begin(kI2cSda, kI2cScl);
      Wire1.begin(kI2cExtSda, kI2cExtScl);
    }
    pinMode(kBtnA, INPUT);
    pinMode(kBtnB, INPUT);
    pinMode(kBtnC, INPUT);
    pinMode(kBtnExt, INPUT_PULLUP);
    pinMode(kBtnPwr, INPUT_PULLUP);
    Power.begin();
    TinyM5::resetPulse(0);
    // The panel holds this line while it refreshes. Nothing here
    // waits on it, but a floating pin would make the driver's first
    // read a coin toss.
    pinMode(4, INPUT);
    return true;
  }

  /// Latch the power rail on. Called by begin(), and safe to call
  /// first thing in setup() when begin() cannot run that early.
  static void holdPower()
  {
    pinMode(kPowerHold, OUTPUT);
    digitalWrite(kPowerHold, HIGH);
  }

  void update()
  {
    const uint32_t ms = millis();
    BtnA.update(ms);
    BtnB.update(ms);
    BtnC.update(ms);
    BtnExt.update(ms);
    BtnPwr.update(ms);
  }

  /// Everything a graphics library needs to drive this panel. This
  /// library owns no driver and draws nothing.
  static constexpr TinyM5::Display display()
  {
    return TinyM5::Display{
        /*bus*/ TinyM5::DisplayBus::Spi,
        /*mosi*/ 23, /*miso*/ 34, /*sclk*/ 18,
        /*dc*/ 15, /*cs*/ 9,
        /*io2*/ -1, /*io3*/ -1,
        /*rst*/ -1,  // begin() has already pulsed it
        /*busy*/ 4,
        /*freqWrite*/ 40000000, /*freqRead*/ 16000000,
        /*width*/ 200, /*height*/ 200,
        /*offsetX*/ 0, /*offsetY*/ 0,
        /*rotation*/ 0, /*invert*/ false,
        /*threeWire*/ true};
  }

  static constexpr const char *getBoardName() { return kName; }
  static constexpr TinyM5::BoardId getBoard() { return kBoardId; }

  static constexpr int8_t getPin(TinyM5::Pin pin)
  {
    switch (pin) {
      case TinyM5::Pin::InI2cSda: return kI2cSda;
      case TinyM5::Pin::InI2cScl: return kI2cScl;
      case TinyM5::Pin::ExI2cSda: return kI2cExtSda;
      case TinyM5::Pin::ExI2cScl: return kI2cExtScl;
      case TinyM5::Pin::RgbLed: return kRgbLed;
      case TinyM5::Pin::PowerHold: return kPowerHold;
    }
    return -1;
  }
};

// The same answers for the preprocessor.
//
// `if constexpr` cannot stand in for these. Outside a template both
// arms of an `if constexpr` still go through name lookup, so a sketch
// that reaches for Board.Power on a board without a battery fails to
// compile even in the branch that is discarded. Absent hardware is
// absent rather than stubbed out, so portable sketches need #if.
#define TINYM5_HAS_DISPLAY 1
#define TINYM5_HAS_BACKLIGHT 0
#define TINYM5_HAS_BATTERY 1
#define TINYM5_HAS_DISPLAY_DSI 0
#define TINYM5_HAS_INTERNAL_I2C 1
#define TINYM5_HAS_EXTERNAL_I2C 1
#define TINYM5_HAS_RGB_LED 0
#define TINYM5_HAS_BTN_A 1
#define TINYM5_HAS_BTN_B 1
#define TINYM5_HAS_BTN_C 1
#define TINYM5_HAS_BTN_EXT 1
#define TINYM5_HAS_BTN_PWR 1

// The board this sketch drives, written once so that portable code can
// name it without naming the product.
#define TINYM5_BOARD TinyM5BoardCoreInk

#ifndef TINYM5_NO_GLOBAL_BOARD
// Deliberately not called `M5`: M5Unified defines a global of that name
// (M5Unified.cpp:58), so sharing it would break any sketch that also
// pulls in one of the official Unit libraries.
inline TinyM5BoardCoreInk Board;
#endif
