// What Board.begin() does on the M5Station, recorded for the golden.
//
// The include is the spelling the README recommends, so the test walks
// the same path a user does.
//
// Generated by tools/gen_boards.py.
#include <TinyM5BoardStation.h>
#include <tinym5_trace.h>
#include <tinym5_model_i2c.h>

void setup()
{
  Serial.begin(115200);
  TinyM5Trace::start("Station");

  // The AXP192 has to answer or begin() stops at its detection read and
  // the rest of the trace never happens.
  TinyM5Trace::useChip(0, 0x34, 0x03, 0x03);
  // 0xE34 counts at 1.1 mV each == 4000 mV, so the golden shows whether
  // the conversion is right rather than just plausible.
  TinyM5Trace::model().set(0x78, 0xE3);
  TinyM5Trace::model().set(0x79, 0x04);

  Board.begin();

  TinyM5Trace::finish();
}

void loop() { delay(10); }
