// What Board.begin() does on the M5TimerCam, recorded for the golden.
//
// The include is the spelling the README recommends, so the test walks
// the same path a user does.
//
// Generated by tools/gen_boards.py.
#include <TinyM5BoardTimerCam.h>
#include <tinym5_trace.h>

void setup()
{
  Serial.begin(115200);
  TinyM5Trace::start("TimerCam");

  // 2000 mV at the pin, so the golden shows what this board's
  // divider ratio makes of it.
  HostArduino::setAnalogMilliVolts(38, 2000);

  Board.begin();

  TinyM5Trace::finish();
}

void loop() { delay(10); }
